# Generated by Django 3.1.1 on 2020-09-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('course_no', models.IntegerField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('student_no', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('contact', models.IntegerField()),
                ('course', models.ManyToManyField(to='app.CourseModel')),
            ],
        ),
    ]
